version: '3.1'

services:
  fastapi:
    build: ./app/
    restart: always
    container_name: fuba_api
    ports:
      - '8000:8000'

  mariadb:
    build: ./db/
    restart: always
    container_name: fuba_db
    ports:
      - '3306:3306'