version: '3.1'

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: d03e94c3
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data/fussballstatistiken.sql:/docker-entrypoint-initdb.d/fussballstatistiken.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d/
    ports:
      - '8080:80'

  fastapi:
    build: .
    restart: always
    container_name: fastapi
    ports:
      - '8000:8000'
