apiVersion: v1
kind: Service
metadata:
  name: fuba
  labels:
    app: fuba
spec:
  ports:
    - port: 8080
      targetPort: 8000
  selector:
    app: fuba
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuba
  labels:
    app: fuba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fuba
  template:
    metadata:
      labels:
        app: fuba
    spec:
      volumes:
        - name: secret
          secret:
            secretName: mariadb-secret
        - name: config
          secret:
            secretName: fuba-config
      containers:
      - name: fuba
        image: localhost:5005/fwpm_docker-fastapi:latest
        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: fuba-config
                key: db-host
          - name: DB_PW
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-root-password
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  mariadb-root-password: aklPRkpJbzIzNWppZkFKZmkzNGFwaWhp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fuba-config
data:
  db-host: mariadb.default.svc.cluster.local

